import {
  Atom,
  Award,
  BadgeCheck,
  BookOpen,
  Brain,
  Calculator,
  CircleHelp,
  Ellipsis,
  Ear,
  FlaskConical,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  Heart,
  Languages,
  LaptopMinimalCheck,
  MapPinned,
  MessageSquareQuote,
  MonitorSmartphone,
  PenLine,
  PenTool,
  SlidersHorizontal,
  Sparkles,
  Speech,
  Target,
  Timeline,
  UserRound,
  UsersRound,
  Zap,
} from 'lucide-react';

export const iconMap = {
  atom: Atom,
  award: Award,
  'badge-check': BadgeCheck,
  'book-open': BookOpen,
  brain: Brain,
  calculator: Calculator,
  'circle-help': CircleHelp,
  ellipsis: Ellipsis,
  ear: Ear,
  'flask-conical': FlaskConical,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  handshake: Handshake,
  heart: Heart,
  'heart-handshake': HandHeart,
  languages: Languages,
  'laptop-minimal-check': LaptopMinimalCheck,
  'map-pinned': MapPinned,
  'message-square-quote': MessageSquareQuote,
  'monitor-smartphone': MonitorSmartphone,
  'pen-line': PenLine,
  'pen-tool': PenTool,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  speech: Speech,
  target: Target,
  timeline: Timeline,
  'user-round': UserRound,
  'users-round': UsersRound,
  zap: Zap,
};

export function IconByKey({ iconKey, size = 18, strokeWidth = 2, className = '', ...props }) {
  const Icon = iconMap[iconKey] ?? Sparkles;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} {...props} />;
}

